import {
	readFileSync,
	writeFileSync,
	chmodSync,
	copyFileSync,
	existsSync,
	mkdirSync,
	rmSync,
} from "node:fs";
import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = fileURLToPath(new URL(".", import.meta.url));
import { exec, execSync } from "node:child_process";
const execAsync = promisify(exec);
import { promisify } from "node:util";
import { defineConfig } from "@rspack/cli";
import {
	rspack,
	type ExternalsType,
	type ExternalItemFunctionData,
	type ExternalItemValue,
	type Mode,
	type RspackOptions,
	type WebpackCompiler,
} from "@rspack/core";
import { RsdoctorRspackPlugin } from "@rsdoctor/rspack-plugin";
import { TsCheckerRspackPlugin } from "ts-checker-rspack-plugin";
function nodeExternals(
	{ context, request }: ExternalItemFunctionData,
	callback: (
		err?: Error,
		result?: ExternalItemValue,
		type?: ExternalsType,
	) => void,
) {
	if (!/^(\.|\/|[A-Za-z]:[\\/])/.test(request || "")) {
		return callback(undefined, request);
	}

	callback();
}

function extractRuntimeExportNames(source: string): string[] {
	const names = new Set<string>();

	const esmMatches = source.matchAll(/export\s*\{([^}]+)\}\s*;/g);
	for (const m of esmMatches) {
		for (const part of m[1].split(",")) {
			const trimmed = part.trim();
			if (!trimmed) continue;
			const asMatch = trimmed.match(/\s+as\s+([A-Za-z_$][\w$]*)\s*$/);
			const name = asMatch
				? asMatch[1]
				: trimmed.match(/^([A-Za-z_$][\w$]*)/)?.[1];
			if (name) names.add(name);
		}
	}
	if (names.size > 0) return [...names];

	const defMatches = [
		...source.matchAll(
			/\b[A-Za-z_$][\w$]*\.d\([A-Za-z_$][\w$]*,\s*\{([\s\S]*?)\}\)/g,
		),
	];
	if (defMatches.length > 0) {
		const last = defMatches[defMatches.length - 1][1];
		for (const m of last.matchAll(/([A-Za-z_$][\w$]*)\s*:/g)) {
			names.add(m[1]);
		}
	}
	return [...names];
}

function renderExternalStub(names: string[], globalName: string): string {
	const sorted = [...names].sort();
	return [
		"// generated by ExternalStubPlugin",
		`// exports from globalThis.${globalName} (set by the IIFE bundle).`,
		`const __external = /** @type {any} */ (globalThis).${globalName};`,
		"export const {",
		...sorted.map((n) => `\t${n},`),
		"} = __external;",
		"",
	].join("\n");
}

class ExternalStubPlugin {
	bundleFilename: string;
	stubFilename: string;
	globalName: string;
	outputDir: string;

	constructor(opts: {
		bundleFilename: string;
		stubFilename: string;
		globalName: string;
		outputDir: string;
	}) {
		this.bundleFilename = opts.bundleFilename;
		this.stubFilename = opts.stubFilename;
		this.globalName = opts.globalName;
		this.outputDir = opts.outputDir;
	}

	apply(compiler: WebpackCompiler) {
		compiler.hooks.afterEmit.tap("ExternalStubPlugin", () => {
			const bundlePath = join(this.outputDir, this.bundleFilename);
			const stubPath = join(this.outputDir, this.stubFilename);
			let source: string;
			try {
				source = readFileSync(bundlePath, "utf-8");
			} catch (e: any) {
				console.error(
					`ExternalStubPlugin: cannot read ${bundlePath}: ${e.message}`,
				);
				return;
			}

			const names = extractRuntimeExportNames(source);
			if (names.length === 0) {
				console.warn(
					`ExternalStubPlugin: no exports discovered in ${bundlePath}; stub not written`,
				);
				return;
			}

			const stub = renderExternalStub(names, this.globalName);
			writeFileSync(stubPath, stub);
			console.log(
				`ExternalStubPlugin: wrote ${this.stubFilename} (${names.length} exports → globalThis.${this.globalName})`,
			);
		});
	}
}

class TypeScriptDeclarationsPlugin {
	dir: string;
	tsconfigName: string;
	useAlias: boolean;
	tempDir: string;

	constructor(
		dir: string,
		tempDir: string,
		tsconfigName: string = "tsconfig.types.json",
		useAlias: boolean = true,
	) {
		this.dir = dir;
		this.tempDir = tempDir;
		this.tsconfigName = tsconfigName;
		this.useAlias = useAlias;
	}

	apply(compiler: WebpackCompiler) {
		compiler.hooks.afterEmit.tapPromise(
			"TypeScriptDeclarationsPlugin",
			async () => {
				const { stdout } = await execAsync(
					`pnpm exec tsc --project ${this.tsconfigName}`,
					{ cwd: this.dir },
				);
				if (stdout) console.log(stdout);
				if (this.useAlias) {
					await execAsync(
						`pnpm exec tsc-alias --project ${this.tsconfigName}`,
						{ cwd: this.dir },
					);
				}
				if (this.dir === controllerdir) {
					await execAsync(
						"pnpm exec tsc ../rpc/index.ts --declaration --emitDeclarationOnly --skipLibCheck --target ES2022 --module ESNext --moduleResolution bundler --outDir dist/types/rpc",
						{ cwd: this.dir },
					);
					const entry = join(this.dir, "dist/types/index.d.ts");
					writeFileSync(
						entry,
						readFileSync(entry, "utf8").replaceAll(
							'"@ramjet/rpc"',
							'"./rpc/index"',
						),
					);
				}
				if (this.dir === controllerdir) {
					copyFileSync(
						join(this.dir, "src/types.d.ts"),
						join(this.dir, "dist/types/types.d.ts"),
					);
				}
				if (this.dir === ramjetdir) {
					const wasmTypes = join(this.dir, "dist/types/rewriter/wasm/out");
					mkdirSync(wasmTypes, { recursive: true });
					copyFileSync(
						join(this.dir, "rewriter/wasm/out/wasm.d.ts"),
						join(wasmTypes, "wasm.d.ts"),
					);
					const wrapper = join(
						this.dir,
						"dist/types/shared/rewriters/wasm.d.ts",
					);
					writeFileSync(
						wrapper,
						readFileSync(wrapper, "utf8").replaceAll(
							"../../../rewriter/wasm/out/wasm.js",
							"../../rewriter/wasm/out/wasm",
						),
					);
				}
				const globalTypes = join(this.dir, "src/global.d.ts");
				if (existsSync(globalTypes)) {
					mkdirSync(join(this.dir, "dist/types"), { recursive: true });
					copyFileSync(globalTypes, join(this.dir, "dist/types/global.d.ts"));
				}
				const temporary = resolve(this.dir, this.tempDir);
				if (
					!temporary.startsWith(resolve(this.dir) + "/") &&
					!temporary.startsWith(resolve(this.dir) + "\\")
				) {
					throw new Error("Declaration cleanup must stay inside the package.");
				}
				rmSync(temporary, { recursive: true, force: true });
			},
		);
	}
}

const ramjetdir = join(__dirname, "packages/core");
const controllerdir = join(__dirname, "packages/controller");
const utilsdir = join(__dirname, "packages/utils");
const bootstrapdir = join(__dirname, "packages/bootstrap");
const createproxyappdir = join(__dirname, "packages/create-proxy-app");

const wasmPath = join(ramjetdir, "dist/ramjet.wasm");
let wasmB64: string;
const wasmBuf = await readFile(wasmPath);
wasmB64 = wasmBuf.toString("base64");

export const tsloader = {
	test: /\.ts$/,
	loader: "builtin:swc-loader",
	exclude: ["/node_modules/"],
	options: {
		jsc: {
			parser: {
				syntax: "typescript",
			},
			target: "es2022",
		},
		module: {
			type: "es6",
			strict: false,
			strictMode: false,
		},
	},
	type: "javascript/auto",
};

function deepmerge<T extends any>(target: T, source: Partial<T>): T {
	//@ts-ignore this whole function is a hack
	const output = { ...target };
	if (isObject(target) && isObject(source)) {
		Object.keys(source).forEach((key) => {
			//@ts-ignore this whole function is a hack
			if (isObject(source[key])) {
				//@ts-ignore this whole function is a hack
				if (!(key in target)) Object.assign(output, { [key]: source[key] });
				//@ts-ignore this whole function is a hack
				else output[key] = deepmerge(target[key], source[key]);
			} else {
				//@ts-ignore this whole function is a hack
				Object.assign(output, { [key]: source[key] });
			}
		});
	}
	return output;
}

function isObject(item: any): item is Record<string, unknown> {
	return item && typeof item === "object" && !Array.isArray(item);
}
const rsDoctorPlugin = process.env.DEBUG
	? new RsdoctorRspackPlugin({
			supports: {
				parseBundle: true,
				banner: true,
			},
		})
	: null;
const createGenericConfig = (options: Partial<RspackOptions>) => {
	const def = {
		devtool: "source-map",
		mode: "development" as Mode,
		resolve: {
			extensions: [".ts", ".js"],
		},
		module: {
			rules: [tsloader],
			parser: {
				javascript: {
					overrideStrict: "non-strict",
					dynamicImportMode: "eager",
				},
			},
		},
		plugins: [rsDoctorPlugin],
		optimization: {
			minimizer: [
				new rspack.SwcJsMinimizerRspackPlugin({
					minimizerOptions: {
						module: options.output?.libraryTarget === "module",
					},
				}),
			],
		},
	};
	return defineConfig(
		deepmerge<RspackOptions>(def as unknown as RspackOptions, options),
	);
};

type RamjetBuildConfig = {
	entry: RspackOptions["entry"];
	output: RspackOptions["output"];
	rewriterWasm: string;
	extraConfig?: Partial<RspackOptions>;
	name: string;
};

const createRamjetConfig = (options: RamjetBuildConfig) => {
	const { entry, output, rewriterWasm, extraConfig = {}, name } = options;

	return createGenericConfig({
		name,
		entry,
		resolve: {
			alias: {
				"@rewriters": join(ramjetdir, "src/shared/rewriters"),
				"@client": join(ramjetdir, "src/client"),
				"@": join(ramjetdir, "src"),
			},
		},
		output,
		plugins: [
			new rspack.ProvidePlugin({
				dbg: [join(ramjetdir, "src/log.ts"), "default"],
			}),
			new rspack.DefinePlugin({
				REWRITERWASM: rewriterWasm,
			}),
			new rspack.DefinePlugin({
				VERSION: JSON.stringify(sjpackagemeta.version),
			}),
			new rspack.DefinePlugin({
				COMMITHASH: (() => {
					try {
						const hash = JSON.stringify(
							execSync("git rev-parse --short HEAD", {
								encoding: "utf-8",
							}).replace(/\r?\n|\r/g, ""),
						);

						return hash;
					} catch {
						return JSON.stringify("unknown");
					}
				})(),
			}),
			new rspack.DefinePlugin({
				BUILDDATE: JSON.stringify(new Date().toISOString()),
			}),
		],
		target: "webworker",
		ignoreWarnings: [
			{
				module: /src\/entry\.ts/,
				message:
					/Critical dependency: the request of a dependency is an expression/,
			},
		],
		...extraConfig,
	});
};

const sjpackagemeta = JSON.parse(
	await readFile(join(ramjetdir, "package.json"), "utf-8"),
);

const iifeConfig = createRamjetConfig({
	name: "ramjet-iife",
	entry: {
		main: join(ramjetdir, "src/index.ts"),
	},
	output: {
		filename: "ramjet.js",
		path: join(ramjetdir, "dist"),
		iife: true,
		library: {
			type: "assign",
			name: "self.$ramjet",
		},
	},
	rewriterWasm: "undefined",
	extraConfig: {
		performance: {
			hints: false,
		},
	},
});

const iifeBundledConfig = createRamjetConfig({
	name: "ramjet-iife-bundled",
	entry: {
		bundled: join(ramjetdir, "src/index.ts"),
	},
	output: {
		filename: "ramjet_bundled.js",
		path: join(ramjetdir, "dist"),
		iife: true,
		library: {
			type: "assign",
			name: "self.$ramjet",
		},
	},
	rewriterWasm: JSON.stringify(wasmB64),
	extraConfig: {
		performance: {
			hints: false,
		},
	},
});

const moduleConfig = createRamjetConfig({
	name: "ramjet-esmodule",
	entry: {
		bundle: join(ramjetdir, "src/index.ts"),
	},
	output: {
		filename: "ramjet.mjs",
		path: join(ramjetdir, "dist"),
		libraryTarget: "module",
		iife: false,
	},

	rewriterWasm: "undefined",
	extraConfig: {
		performance: {
			hints: false,
		},
		experiments: {
			outputModule: true,
		},
	},
});
moduleConfig.plugins!.push(
	new ExternalStubPlugin({
		bundleFilename: "ramjet.mjs",
		stubFilename: "ramjet-external.mjs",
		globalName: "$ramjet",
		outputDir: join(ramjetdir, "dist"),
	}),
);

const moduleBundledConfig = createRamjetConfig({
	name: "ramjet-esmodule-bundled",
	entry: {
		bundle: join(ramjetdir, "src/index.ts"),
	},
	output: {
		filename: "ramjet_bundled.mjs",
		path: join(ramjetdir, "dist"),
		libraryTarget: "module",
		iife: false,
	},
	rewriterWasm: JSON.stringify(wasmB64),
	extraConfig: {
		performance: {
			hints: false,
		},
		experiments: {
			outputModule: true,
		},
	},
});

const typeGenConfig = defineConfig({
	context: ramjetdir,
	entry: {
		index: "./src/index.ts",
	},
	output: {
		path: join(ramjetdir, "dist/temp-types-build"),
		filename: "[name].js",
	},
	plugins: [
		new TypeScriptDeclarationsPlugin(
			ramjetdir,
			"dist/temp-types-build",
			"tsconfig.types.json",
			true,
		),
	],
	resolve: {
		extensions: [".ts", ".js"],
		alias: {
			"@rewriters": join(ramjetdir, "src/shared/rewriters"),
			"@client": join(ramjetdir, "src/client"),
			"@": join(ramjetdir, "src"),
		},
	},
	module: {
		rules: [tsloader],
	},
});

const controllermeta = JSON.parse(
	await readFile(join(controllerdir, "package.json"), "utf-8"),
);
const controllerVersionDefines = new rspack.DefinePlugin({
	RAMJET_EXPECTED_VERSION: JSON.stringify(sjpackagemeta.version),
	CONTROLLER_VERSION: JSON.stringify(controllermeta.version),
});

const controllerConfig = createGenericConfig({
	name: "ramjet-controller",
	dependencies: ["ramjet-esmodule"],
	entry: {
		api: join(controllerdir, "src/index.ts"),
		inject: join(controllerdir, "src/inject.ts"),
		sw: join(controllerdir, "src/sw.ts"),
	},
	output: {
		filename: "controller.[name].js",
		path: join(controllerdir, "dist"),
		iife: true,
		library: {
			type: "var",
			name: "$ramjetController",
		},
	},
	target: "web",
	plugins: [
		controllerVersionDefines,
		new ExternalStubPlugin({
			bundleFilename: "controller.api.js",
			stubFilename: "controller-external.mjs",
			globalName: "$ramjetController",
			outputDir: join(controllerdir, "dist"),
		}),
		new TypeScriptDeclarationsPlugin(
			controllerdir,
			"dist/temp-types-build",
			"tsconfig.types.json",
			false,
		),
	],
});

const utilsVersionDefines = new rspack.DefinePlugin({
	RAMJET_EXPECTED_VERSION: JSON.stringify(sjpackagemeta.version),
	CONTROLLER_EXPECTED_VERSION: JSON.stringify(controllermeta.version),
});

const utilsIifeConfig = createGenericConfig({
	name: "ramjet-utils-iife",
	dependencies: ["ramjet-esmodule", "ramjet-controller"],
	entry: {
		main: join(utilsdir, "src/index.ts"),
	},
	output: {
		filename: "ramjet-utils.js",
		path: join(utilsdir, "dist"),
		iife: true,
		library: {
			type: "assign",
			name: "self.$ramjetUtils",
		},
	},
	target: "web",
	plugins: [
		utilsVersionDefines,
		new TypeScriptDeclarationsPlugin(
			utilsdir,
			"dist/temp-types-build",
			"tsconfig.types.json",
			false,
		),
	],
});

const utilsModuleConfig = createGenericConfig({
	name: "ramjet-utils-esmodule",
	dependencies: ["ramjet-esmodule", "ramjet-controller"],
	entry: {
		main: join(utilsdir, "src/index.ts"),
	},
	output: {
		filename: "ramjet-utils.mjs",
		path: join(utilsdir, "dist"),
		libraryTarget: "module",
		iife: false,
	},
	experiments: {
		outputModule: true,
	},
	target: "web",
	plugins: [
		utilsVersionDefines,
		new TypeScriptDeclarationsPlugin(
			utilsdir,
			"dist/temp-types-build",
			"tsconfig.types.json",
			false,
		),
	],
});

const bootstrapConfig = createGenericConfig({
	name: "ramjet-bootstrap",
	entry: {
		server: join(bootstrapdir, "src/server.ts"),
		client: join(bootstrapdir, "src/client.ts"),
	},
	output: {
		filename: "bootstrap-[name].js",
		path: join(bootstrapdir, "dist"),
		iife: false,
		libraryTarget: "module",
	},
	experiments: {
		outputModule: true,
	},
	target: "node",
	externals: [nodeExternals],
	module: {
		parser: {
			javascript: {
				importMeta: false,
			},
		},
	},
	plugins: [
		new TypeScriptDeclarationsPlugin(
			bootstrapdir,
			"dist/temp-types-build",
			"tsconfig.types.json",
			false,
		),
	],
});

const bootstrapStaticConfig = createGenericConfig({
	name: "ramjet-bootstrap-static",
	entry: {
		static: join(bootstrapdir, "src/static.ts"),
	},
	output: {
		filename: "bootstrap-[name].js",
		path: join(bootstrapdir, "dist"),
		iife: true,
	},
});

const createProxyAppConfig = createGenericConfig({
	name: "create-ramjet-app",
	entry: {
		index: join(createproxyappdir, "src/index.ts"),
	},
	output: {
		path: join(createproxyappdir, "dist"),
		filename: "[name].js",
		libraryTarget: "module",
		iife: false,
	},
	experiments: {
		outputModule: true,
	},
	target: "node",
	module: {
		parser: {
			javascript: {
				importMeta: false,
			},
		},
	},
	plugins: [
		new rspack.BannerPlugin({
			banner: "#!/usr/bin/env node",
			raw: true,
			entryOnly: true,
		}),
	],
});

export default [
	iifeConfig,
	iifeBundledConfig,
	moduleConfig,
	moduleBundledConfig,
	typeGenConfig,
	controllerConfig,
	utilsIifeConfig,
	utilsModuleConfig,
	bootstrapConfig,
	bootstrapStaticConfig,
	createProxyAppConfig,
];
